name: Assembly and push in lune.su

on:
  push:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout MounTemed/lune-template
        uses: actions/checkout@v4.2.2

      - name: Set up Node.js and Bun
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: npm install -g bun

      - name: Update dependencies, then run build
        run: |
          bun install
          bun run build --outDir ./dist/frontend/

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push app
        uses: docker/build-push-action@v6
        with:
          file: ./dist/Containerfile
          context: ./dist/
          push: true
          tags: docker.io/${{ secrets.DOCKER_USER }}/luneapp:latest
